Add python code coverage

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -95,7 +95,8 @@ jobs:
         source env/activate
         export LD_LIBRARY_PATH="/opt/ttmlir-toolchain/lib/:${{ steps.strings.outputs.install-output-dir }}/lib:${{ steps.strings.outputs.build-output-dir }}/lib:./lib/:${LD_LIBRARY_PATH}"
         pytest -v tests/torch \
-           --junit-xml=${{ steps.strings.outputs.test_report_path_torch }}
+           --junit-xml=${{ steps.strings.outputs.test_report_path_torch }} \
+           --cov=tests/torch --cov-append
 
     - name: Upload Test Report Torch
       uses: actions/upload-artifact@v4
@@ -147,7 +148,8 @@ jobs:
                   tests/models/torchvision/test_torchvision_image_classification.py::test_torchvision_image_classification[full-regnet_x_8gf] \
                   tests/models/torchvision/test_torchvision_image_classification.py::test_torchvision_image_classification[full-regnet_x_16gf] \
                   tests/models/torchvision/test_torchvision_image_classification.py::test_torchvision_image_classification[full-regnet_x_32gf] \
-           --junit-xml=${{ steps.strings.outputs.test_report_path_models }}
+           --junit-xml=${{ steps.strings.outputs.test_report_path_models }} \
+           --cov=tests/models --cov-append
 
     - name: Upload Test Report Models
       uses: actions/upload-artifact@v4
@@ -162,7 +164,8 @@ jobs:
         source env/activate
         export LD_LIBRARY_PATH="/opt/ttmlir-toolchain/lib/:${{ steps.strings.outputs.install-output-dir }}/lib:${{ steps.strings.outputs.build-output-dir }}/lib:./lib/:${LD_LIBRARY_PATH}"
         pytest -v tests/onnx \
-            --junit-xml=${{ steps.strings.outputs.test_report_path_onnx }}
+            --junit-xml=${{ steps.strings.outputs.test_report_path_onnx }} \
+            --cov=tests/onnx --cov-append
 
     - name: Upload Test Report Onnx
       uses: actions/upload-artifact@v4
@@ -182,13 +185,13 @@ jobs:
         detailed_summary: true
         group_suite: true
 
-    - name: Prepare code coverage report
-      if: success() || failure()
-      continue-on-error: true
-      run: |
-        lcov --directory . --capture --output-file coverage.info
-        # lcov --extract coverage.info '**/tt_torch/csrc/*' --output-file coverage.info
-        lcov --list coverage.info
+    # - name: Prepare code coverage report
+    #   if: success() || failure()
+    #   continue-on-error: true
+    #   run: |
+    #     lcov --directory . --capture --output-file coverage.info
+    #     # lcov --extract coverage.info '**/tt_torch/csrc/*' --output-file coverage.info
+    #     lcov --list coverage.info
 
     - name: Upload coverage reports to Codecov
       if: success() || failure()
@@ -196,7 +199,7 @@ jobs:
       uses: codecov/codecov-action@v5
       with:
         files: coverage.info
-        disable_search: true
+        # disable_search: true
         token: ${{ secrets.CODECOV_TOKEN }}
 
     - name: Upload test results to Codecov
