Few op-by-op flow improvements (xfail output shown, better tar-results error) and fixes (use self.tokenizer) to models (#453)
### Ticket
See #451 for details - Closes #451

### Problem description
Address a few concerns from this ticket.

- A couple categories of test fixes after Lewis' change at 0decda6 that
prevented models from running (use self.tokenizer, and is_token_output).
There are other issues exposed by whisper, musicgen that will require
followup debug/fixes.
- Add better error message in "Tar results" when $pwd (test output dir)
used as working-directory doesn't exist (was occuring in these xfail
tests that failed to run)
- Add `--runxfail` arg to op-by-op flow so we can at least see xfail
test output in log files instead of nothing (useful for when signature
changes, but we don't know, happened today)
  
### Checklist
- [x] New/Existing tests provide coverage for changes

codegen model is back to passing in op-by-op flow with these changes.

diff --git a/.github/workflows/run-op-by-op-model-tests.yml b/.github/workflows/run-op-by-op-model-tests.yml
--- a/.github/workflows/run-op-by-op-model-tests.yml
+++ b/.github/workflows/run-op-by-op-model-tests.yml
@@ -313,7 +313,7 @@ jobs:
 
           pytest_log="test_${counter}.log"
 
-          pytest -svv "$test_case" --op_by_op_torch > "$pytest_log" 2>&1
+          pytest -svv --runxfail "$test_case" --op_by_op_torch > "$pytest_log" 2>&1
           exit_code=$?
 
           echo "====== BEGIN LOG: $test_case ======" >> full_job_output.log
@@ -340,9 +340,17 @@ jobs:
     - name: Tar results
       if: success() || failure()
       shell: bash
-      working-directory: ${{ steps.strings.outputs.test-output-dir }}
       run: |
-        tar cvf ${{ matrix.build.name }}_${{ steps.fetch-job-id.outputs.job_id }}.tar .
+        TEST_DIR="${{ steps.strings.outputs.test-output-dir }}"
+        OUTPUT_TAR="${{ matrix.build.name }}_${{ steps.fetch-job-id.outputs.job_id }}.tar"
+
+        if [ ! -d "$TEST_DIR" ]; then
+          echo "ERROR: Test output dir '$TEST_DIR' does not exist. Please check if test ran properly."
+          exit 1
+        fi
+
+        cd "$TEST_DIR"
+        tar cvf "$OUTPUT_TAR" .
 
     - name: Upload test folder to archive
       if: success() || failure()
