Isolate Full Model Execute Pytest Processes and Quarantine Bert (#562)
### Ticket
None

### Problem description
Full model pytests are run in a single invocation of pytest and
therefore generate a single test report and run in a single process.
Process-killing failures are rare, but will cause the report to not be
generated.

### What's changed
- Isolate full execute pytest processes so each generates individual
report
- Restore op-by-op and compile jobs temporarily removed earlier today

### Checklist
- [x] New/Existing tests provide coverage for changes
- [x] CollectData job picks up all pytest results even though they are
written to unique files. Post-processed report JSONs look well formed on
inspection and are queryable from Superset

diff --git a/.github/workflows/run-full-model-execution-tests.yml b/.github/workflows/run-full-model-execution-tests.yml
--- a/.github/workflows/run-full-model-execution-tests.yml
+++ b/.github/workflows/run-full-model-execution-tests.yml
@@ -125,6 +125,8 @@ jobs:
         echo "install-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
         echo "dist-dir=$(pwd)/dist" >> "$GITHUB_OUTPUT"
         echo "test_report_path_models=report_models_$JOB_ID.xml" >> "$GITHUB_OUTPUT"
+        echo "test_report_dir=$(pwd)/test-reports" >> "$GITHUB_OUTPUT"
+
     - name: Use build artifacts
       uses: actions/download-artifact@v4
       with:
@@ -154,16 +156,48 @@ jobs:
       run: |
         source env/activate
 
-        pytest --durations=50 -v ${{matrix.build.tests}} \
-          --junit-xml=${{ steps.strings.outputs.test_report_path_models }} \
-          --cov=tt_torch --cov-report term --cov-report xml:coverage.xml --cov-append
+        mkdir -p ${{ steps.strings.outputs.test_report_dir }}
+
+        # prevent script termination on failure
+        set +e
+
+        failure=0
+
+        # Split the test string into individual tests and run them one by one
+        echo "${{ matrix.build.tests }}" | tr ' ' '\n' | while read -r test; do
+          if [[ -n "$test" ]]; then
+            echo "Running test: $test"
+            report_file="${{ steps.strings.outputs.test_report_dir }}/$(echo $test | tr '/' '_' | tr ':' '_')__${{ steps.strings.outputs.test_report_path_models }}"
+            echo "JUnitXML logged to $report_file"
+
+            pytest --durations=0 -v "$test" \
+              --junit-xml="$report_file" \
+              --cov=tt_torch --cov-report term --cov-report xml:coverage.xml --cov-append
+            # Check the return code of pytest
+            if [[ $? -ne 0 ]]; then
+              echo "Test failed: $test"
+              failure=1
+            fi
+          fi
+        done
+
+        set -e
+
+        # Exit with the appropriate code
+        if [[ $failure -ne 0 ]]; then
+          echo "One or more tests failed."
+          exit 1
+        else
+          echo "All tests passed."
+          exit 0
+        fi
 
     - name: Upload Test Report Models
       uses: actions/upload-artifact@v4
       if: success() || failure()
       with:
         name: test-reports-models-${{ matrix.build.runs-on }}-${{ matrix.build.name }}-${{ steps.fetch-job-id.outputs.job_id }}
-        path: ${{ steps.strings.outputs.test_report_path_models }}
+        path: ${{ steps.strings.outputs.test_report_dir }}
 
     - name: Upload coverage reports to Codecov
       if: ${{ (success() || failure()) && inputs.run-codecov == 'true' }}
